catalogo_empresas_homepage:
    path:     /
    defaults: { _controller: CatalogoEmpresasBundle:Default:index }

catalogo_empresas_catalogo:
    path:     /CatalogoEmpresas
    defaults: { _controller: CatalogoEmpresasBundle:Default:CatalogoEmpresas}
    