catalogo_empresas_homepage:
    path:     /
    defaults: { _controller: CatalogoEmpresasBundle:Default:index }

catalogo_empresas_catalogo:
    path:     /CatalogoEmpresas
    defaults: { _controller: CatalogoEmpresasBundle:Default:CatalogoEmpresas}

catalogo_vistas:
    path:     /adminVistas
    defaults: { _controller: CatalogoEmpresasBundle:Default:CatalogoVistas}
    
catalogo_vistas_InsertarVista:
    path:     /InsertarVista
    defaults: { _controller: CatalogoEmpresasBundle:Default:InsertarVista}

catalogo_vistas_InsertarVistaConteo:
    path:     /AdminVistasConteo
    defaults: { _controller: CatalogoEmpresasBundle:Default:VistasConteo}
        
    