catalogo_empresas_homepage:
    path:     /
    defaults: { _controller: CatalogoEmpresasBundle:Default:index }

catalogo_empresas_catalogo:
    path:     /CatalogoEmpresas
    defaults: { _controller: CatalogoEmpresasBundle:Default:CatalogoEmpresas}

catalogo_empresa_vista:
    path:     /InsertarEmpresaVista
    defaults: { _controller: CatalogoEmpresasBundle:Default:InsertarEmpresaVista}

catalogo_vistas:
    path:     /adminVistas
    defaults: { _controller: CatalogoEmpresasBundle:Default:CatalogoVistas}
<<<<<<< HEAD

usuarios_admin:
    path:     /adminUsuarios
    defaults: { _controller: UsuariosBundle:Default:AdminUsuarios }
    
    
=======
catalogo_vistas_InsertarVista:
    path:     /InsertarVista
    defaults: { _controller: CatalogoEmpresasBundle:Default:InsertarVista}
        
    
>>>>>>> 116593c06251cedd921571a2d6e2ddf15cc819a9
