control_acceso_homepage:
    path:     /
    defaults: { _controller: ControlAccesoBundle:Default:index }

control_acceso_login:
    path:     /login
    defaults: { _controller: ControlAccesoBundle:Default:loginUsuario }

control_acceso_insertar:
    path:     /insertarLoginUsuario
    defaults: { _controller: ControlAccesoBundle:Default:InsertarUsuario }

login_check:
    path:   /login_check
    
logout:
    path:   /logout
    defaults:  { _controller: ControlAccesoBundle:Default:logout }

