empresa_homepage:
    path:     /
    defaults: { _controller: EmpresaBundle:Default:index }

empresa_admin:
    path:     /adminEmpresas
    defaults: { _controller: EmpresaBundle:Default:AdminEmpresas }

empresa_admin_insertar:
    path:     /insertarEmpresa
    defaults: { _controller: EmpresaBundle:Default:insertarEmpresa }
    