empresa_homepage:
    path:     /
    defaults: { _controller: EmpresaBundle:Default:index }

empresa_admin:
    path:     /adminEmpresas
    defaults: { _controller: EmpresaBundle:Default:AdminEmpresas }

usuarios_admin:
    path:     /adminUsuarios
    defaults: { _controller: EmpresaBundle:Default:AdminUsuarios }
    