usuarios_homepage:
    path:     /
    defaults: { _controller: UsuariosBundle:Default:index }

usuarios_admin:
    path:     /adminUsuarios
    defaults: { _controller: UsuariosBundle:Default:AdminUsuarios }

usuario_admin_insertar:
    path:     /insertarUsuario
    defaults: { _controller: UsuariosBundle:Default:insertarUsuario }
    
usuario_admin_eliminar:
    path:     /eliminarUsuario
    defaults: { _controller: UsuariosBundle:Default:eliminarUsuario }

usuario_admin_actualizar:
    path:     /actualizarUsuario
    defaults: { _controller: UsuariosBundle:Default:actualizarUsuario }

